### ISSUE TITLE
refactoring recipe doesn't work with compile errors

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/spring-tools#1064]
Steps to reproduce:
- I have a simple project that has a dependency on a random library
- Now the library changes the name of a method and I change the dependency in my ´pom.xml` to point to the new version of the library
- As expected, compiler errors showing up for the method invocations, since my source code still uses the old method name
- There is a recipe in YAML that looks like this:

```
---
type: specs.openrewrite.org/v1beta/recipe
name: com.yourorg.AdaptToNewVersionOfLibrary
displayName: Adapt to changed method of Movie Service
recipeList:
  - org.openrewrite.java.ChangeMethodName:
      methodPattern: com.example.testlib.library.MovieService getMovies(..)
      newMethodName: getAllMovies
```

But when I execute this recipe, it doesn't do anything.

When I switch back to use the old version of the library, the compile errors go away again. Then, I can execute the recipe and it switches my method invocations to the new method name. Then, I can change the dependency in the `pom.xml` file to point to the new version and everything is fine, but the flow is still problematic.

Why is the recipe not able to update the method invocation? I guess this is due to the OpenRewrite parsing not being able to resolve the method invocation (this the old method doesn't exist anymore) and therefore doesn't match that against the method pattern in the recipe.
