### ISSUE TITLE
Unknown property 'url' for type 'VaultConfig' vscode-concourse(YamlSchemaProblem)

### ISSUE THREAD

**Issue by cluedtke** [spring-projects/spring-tools#1534]
**Describe the bug**
concourse-language-server incorrectly [defines `uri`](https://github.com/spring-projects/spring-tools/blob/4e0ec923dd1e16313c88db2e10d2b2397c95ab08/headless-services/concourse-language-server/src/main/java/org/springframework/ide/vscode/concourse/PipelineYmlSchema.java#L524), should instead be `url` according to the docs: https://concourse-ci.org/vars.html#schema.var_source

I know `var_sources` is flagged as "experimental", and `uri` may have been used in the past, but I've been using `url` without issue for the past year.

I'd be happy to raise a PR if you agree with changing `uri` to `url`.

**To Reproduce**
Define a `vault` `var_source` type, with a VaultConfig that includes the correct field, `url`. This gives an error:
> Unknown property 'url' for type 'VaultConfig'vscode-concourse' (YamlSchemaProblem)

**Sample**
```yaml
var_sources:
  - name: vault-aws-engine-account
    type: vault
    config:
      url: https://my-vault-server.io
      path_prefix: aws
      auth_backend: approle
      auth_params:
        role_id: concourse-access-role_id
        secret_id: concourse-access-secret_id
```
